name: PR Validation

on:
  pull_request:
    branches: [develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install -g htmlhint stylelint stylelint-config-standard
      - name: Lint HTML
        run: htmlhint "src/**/*.html"
      - name: Lint CSS
        run: |
          echo '{}' > .stylelintrc.json
          stylelint "**/*.css"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build with Parcel
        run: |
          npm install -D parcel
          npx parcel build src/index.html
